name: Maven Package

on:
  push:
    branches: [release-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Maven dependencies
      uses: actions/cache@v1
      env:
        cache-name: maven
      with:
        path: ~/.m2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Maven project
      run: mvn -B package --file pom.xml

    - name: Publish Maven packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
